### PR TITLE
Dont add permissions to files which have them already

### PR DESCRIPTION
**Pull request by idlewis**
This keeps the container image smaller

### CODE REVIEW

**Comment by idlewis** [comment]
This is to address issue #233 
I have reviewed the chmod operations used in the docker files and can't find any others which I think will affect the image size.

**Comment by jdmcclur** [comment]
Is there a reason this hasn't been reviewed/merged?

**Comment by idlewis** [comment]
@leochr Would you be able to review?

**Comment by leochr** [comment]
@idlewis The permissions didn’t change for the new files added by the featureManager with the proposed changes. Here is what I did:

`docker pull openliberty/open-liberty:kernel-slim-java8-openj9-ubi`
`docker run -d --name ol openliberty/open-liberty:kernel-slim-java8-openj9-ubi`
`docker exec -it ol bash`

Listed files and permissions for /opt/ol/wlp/bin and /opt/ol/wlp/lib : [before_featureUtility.txt](https://github.com/OpenLiberty/ci.docker/files/6094664/before_featureUtility.txt)

Ran featureUtility in container : 
`./opt/ol/wlp/bin/featureUtility installServerFeatures --acceptLicense defaultServer --noCache`

Listed files and permissions again: [after_featureUtility.txt](https://github.com/OpenLiberty/ci.docker/files/6094668/after_featureUtility.txt)

Ran the proposed command in container:
`find /opt/ol/wlp/lib /opt/ol/wlp/bin -perm -g=w ! -perm -g=r -print0 | xargs -0 -r chmod -R g+rw
`

Listed files and permissions again. No changes (same as  _after_featureUtility.txt_): [after_new_command.txt](https://github.com/OpenLiberty/ci.docker/files/6094702/after_new_command.txt)

Ran the old/current command: 
`find /opt/ol/wlp/lib /opt/ol/wlp/bin -perm -g=w -print0 | xargs -0 -r chmod -R g+rw`

Listed files and permissions again. They changed : [after_old_command.txt](https://github.com/OpenLiberty/ci.docker/files/6094717/after_old_command.txt)

**Comment by jdmcclur** [comment]
I think the orginal code is finding any files and **directories** with group write perms and **recursively** granting g+rw (chmod -R) permission. I am not seeing how this is any different than 
```
chmod -R g+rw  /opt/ol/wlp/bin
chmod -R g+rw  /opt/ol/wlp/lib
```

I think this is why Ian's change does not work (as it excludes directories with read perms).

How about
```
find /opt/ol/wlp/bin /opt/ol/wlp/lib -type d -perm -g=w -print0 | xargs -0 -I{} find {} -type f ! -perm -g=rw -print0 | xargs -0 -r chmod g+rw
```
Find folders with write permission, grant rw to the files in those directories if they don't have it.

**Comment by leochr** [comment]
@jdmcclur Tried the command you proposed and the permission of files are same as now. That's great! 

Some folders have different permissions. For example, _/opt/ol/wlp/lib/features_ : 
`drwxrwxr-x 4 default root    4096 Mar  5 15:36 features`      <-- current
`drwxr-xr-x 4 default root    4096 Mar 10 21:14 features`        <-- proposed command

But, I am not certain whether those folders need the write permission. As expected, excluding the `-type f` from the command, keeps the permission of files and folders the same as now.

**Comment by jdmcclur** [comment]
@leochr @idlewis 

It looks like taking out the -type f should work.
```
find /opt/ol/wlp/bin /opt/ol/wlp/lib -type d -perm -g=w -print0 | xargs -0 -I{} find {} ! -perm -g=rw -print0 | xargs -0 -r chmod g+rw
```
My test: 

Before: 2cf3c798bb36   13 minutes ago   |1 VERBOSE=true /bin/sh -c features.sh          69.1MB
After: 6e33911a4bf7   6 minutes ago    |1 VERBOSE=true /bin/sh -c features.sh          **58.1MB**

**Comment by leochr** [comment]
@jdmcclur Thanks for the detailed info. 

We can go with this:

```code
find /opt/ol/wlp/bin /opt/ol/wlp/lib ! -perm -g=rw -print0 | xargs -0 -r chmod g+rw
```

@idlewis could you please make the change? Thanks.

**Comment by leochr** [comment]
With the latest proposed changes the features.sh step went down from 34MB to 22.8MB with kernel-slim's default server config. The permissions were same as the ones with current command:

```
8441b9faccb4   4 minutes ago   /bin/sh -c features.sh                   34MB 
eef97e1f5514     2 minutes ago   /bin/sh -c features.sh                 22.8MB 
```

**Review by leochr — APPROVED** [review]

**Pull request merged**
