### PR TITLE
Delete workarea after SCC run to ensure old server config gets loaded.

### LINKED ISSUE #244: Server uses stale cached server.xml rather than the one copied into the image
Sometimes when I docker build my Open Liberty-based microservice, it ends up not working, because it ignores the server.xml I copy into the image, and instead somehow still uses the built-in server.xml from the base OL image.  When this happens, when I run my image (whether in OpenShift, or just via "docker run"), it doesn't load any of my listed features, but instead just loads `jsp-2.3`.  My Dockerfile is here: https://github.com/IBMStockTrader/broker/blob/master/Dockerfile, and my server.xml is here: https://github.com/IBMStockTrader/broker/blob/master/src/main/liberty/config/server.xml.  Here's the results of running the image I built (which I pushed to the IBM Container Registry at us.icr.io/ibm-stock-trade/broker:error):
```
jalcorn@Johns-MBP-8 broker % docker run -it us.icr.io/ibm-stock-trader/broker:error bash
bash-4.4$ cd /opt/ol/wlp/bin/
bash-4.4$ server run defaultServer

Launching defaultServer (Open Liberty 21.0.0.1/wlp-1.0.48.cl210120210113-1459) on Eclipse OpenJ9 VM, version 11.0.10+9 (en_US)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/keystore.xml
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/open-default-port.xml
[AUDIT   ] CWWKG0028A: Processing included configuration resource: /opt/ol/wlp/usr/servers/defaultServer/includes/basic.xml
[ERROR   ] CWWKF0001E: A feature definition could not be found for jsp-2.3
[AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 3.429 seconds.
^C[AUDIT   ] CWWKE0085I: The server defaultServer is stopping because the JVM is exiting.
[AUDIT   ] CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
[AUDIT   ] CWWKE0036I: The server defaultServer stopped after 7 minutes, 21.027 seconds.
bash-4.4$ exit
```

### PR DESCRIPTION
**Pull request by scottkurz**
Signed-off-by: Scott Kurz <skurz@us.ibm.com>

Fixes #244

### CODE REVIEW

**Comment by scottkurz** [comment]
I'm going to see if I can easily add a recreate test.

**Review by jdmcclur — APPROVED** [review]
I ran some perf measurement. The kernel-slim does start slower, so it takes ~200 ms longer to tell the user that no features are installed, which seems ok to me. Everything else looks good/equivalent to before the change (time to run configure.sh, startup time of final image)

**Comment by scottkurz** [comment]
@leochr did you want to review this or suggest any other reviewer or is this ready to merge?  Thx

**Review by leochr — APPROVED** [review]
Looks good to me

@scottkurz Thanks for the PR! @jdmcclur Thanks for testing the performance!

**Pull request merged**
