### PR TITLE
Merge changes from vNext to main 

### PR DESCRIPTION
**Pull request by wraschke**

### CODE REVIEW

**Review by leochr — COMMENTED** [review]
The `latest` release looks good, but the 23.0.0.7 Ubuntu Dockerfiles need to be updated (to change from multi-stage to single-stage)

The changes from these PRs should be added to 23.0.0.7 to keep it in sync with `latest`. Using the `latest` as the basis would pick these changes as well
https://github.com/OpenLiberty/ci.docker/pull/424
https://github.com/OpenLiberty/ci.docker/pull/428





Leo Christy Jesuraj
  [< 1 minute ago](https://ibm-cloud.slack.com/archives/C055TCDEWCC/p1690292150800249?thread_ts=1690242564.867319&cid=C055TCDEWCC)
The changes from these PRs should be added to 23.0.0.7. Using the latest as the base would pick these changes as well
https://github.com/OpenLiberty/ci.docker/pull/424
https://github.com/OpenLiberty/ci.docker/pull/428

**Comment by leochr** [comment]
@wraschke Updates to Ubuntu 23.0.0.7 looks good. The following fix is still missing from 23.0.0.7's populate_scc.sh
https://github.com/OpenLiberty/ci.docker/pull/428/files

**Comment by mbroz2** [comment]
LGTM (but not marking approved to ensure Leo's feedback is not missed before merging)

**Review by leochr — APPROVED** [review]
@wraschke Looks good. Thank you

**Pull request merged**
