### PR TITLE
Add call to the OpenAPI endpoint during SCC generation

### PR DESCRIPTION
**Pull request by jdmcclur**
Add call to the OpenAPI endpoint during SCC generation. This will improve first request performance.

### CODE REVIEW

**Review by leochr — COMMENTED** [review]
@jdmcclur Thanks for the PR. The new param and the relevant logic looks fine. 

vNext at the moment is 24.0.0.4 (the vNext branch hasn't been updated yet but expect it to be updated in the next day or so). Should this change be backported to 24.0.0.3? or including with latest and 24.0.0.4+ is sufficient?

**Comment by jdmcclur** [comment]
@leochr 24.0.0.4+ is fine.

**Comment by leochr** [comment]
@jdmcclur sounds good. Please remove the changes to the 23.0.0.3 folder. We are still waiting for the 24.0.0.4 baseline to be created. 

Also, it'll be good to update the README to mark these config options with `24.0.0.4+`. Thank you.

**Comment by leochr** [comment]
@jdmcclur Once above comments are addressed, we can merge the changes to the `latest` folder first and then deal with 24.0.0.4. The baseline PR for 24.0.0.4 might carry the changes from the latest folder to the 24.0.0.4 folder, but I am not entirely sure. If it doesn't, then a separate PR for 24.0.0.4 will be needed.

**Comment by leochr** [comment]
@jdmcclur Similar comment as WebSphere Liberty:
24.0.0.4 baseline files were just merged. Please rebase (to add the changes to 24.0.0.4 and remove from 23.0.0.3). Sorry to rush, but we need to get this merged soon, before the builds to produce 24.0.0.4 images with the GM driver are run later today. Thank you.

**Review by leochr — APPROVED** [review]
@jdmcclur Thanks for the rebase/updates. Looks good.

**Pull request merged**
