### PR TITLE
Add images for OpenJDK 11 on OpenJ9

### LINKED ISSUE #42: Docker images based on OpenJ9 with OpenJDK 11
OpenLiberty is planning to support Java 11 soon, and there are already AdoptOpenJDK OpenJ9 docker images available with Java 11:
https://hub.docker.com/r/adoptopenjdk/openjdk11-openj9/

We should create a new set of docker images that are based on these `openjdk11-openj9` builds

### PR DESCRIPTION
**Pull request by aguibert**
Fixes #42

### CODE REVIEW

**Comment by arthurdm** [comment]
Let's wait a bit for this issue: https://github.com/AdoptOpenJDK/openjdk-docker/issues/26  

That would give us a chance to support JDK 11 from the official image, and thus we wouldn't need the community image anymore.

**Comment by arthurdm** [comment]
The top level folder that this PR should target is now called `community`

**Comment by aguibert** [comment]
Followed the chain of issues on the OpenJDK issues you referenced earlier and it looks like it will all come down to this PR getting merged:
https://github.com/docker-library/official-images/pull/5433

Once this gets merged, we should be able to proceed with our official images.

**Comment by arthurdm** [comment]
The Java team is currently consolidating their PRs into a single one, in the hope that it moves into Docker's official repo faster.  If that still does not move quick enough by next week we will probably merge this PR to at least some a version out there.

**Comment by arthurdm** [comment]
Hey @aguibert - we have made some changes to the repo after this PR was created (different top-level directory, and now running as non-root).  When you get a chance can you please update the PR?

**Pull request merged**
