### PR TITLE
add build time option to trust default certs

### PR DESCRIPTION
**Pull request by ezhou365**

### CODE REVIEW

**Comment by brutif** [comment]
@arthurdm Eric's completed testing on this so please merge if you don't see any issues.

**Comment by arthurdm** [comment]
@arturdzm - can you please comment if this will conflict with your recent updates?

**Comment by brutif** [comment]
Hmm, looks like @arturdzm has already implemented equivalent function.  We may need to close this without merging.

**Comment by arturdzm** [comment]
I will add the documentation.
Currently with my changes the trustDefaultCerts is alway set to "true". I am not sure if this ok for all cases.

**Comment by brutif** [comment]
Hi @arturdzm In non-docker environments, we only turn on trustDefaultCerts under two conditions 
 - it's a brand new server created with server create command.
 - user explicitly adds trustDefaultCerts=true to an existing server.xml. 

If a side effect of merely rebuilding a customer image, or redeploying, could be to have trustdefaultcerts flip from off to on without any developer awareness,  my concern would be that customers could perceive this as an accidental reduction in security.   Since it relaxes security, I think it would be safer to have them turn it on explicitly,  although most will want it on. @jtmulvey might disagree with me though.

**Comment by arturdzm** [comment]
Closing in favour of #152

**Pull request closed without merging**
