### PR TITLE
Fix potential max heap issues with OpenJ9 SCCs

### PR DESCRIPTION
**Pull request by ymanton**
Previous versions of OpenJ9 JDK8 ran with a default max heap (`-Xmx`) of 512m. New versions run with a dynamic setting based on the host's available memory (OpenJ9 JDK11 and later have always used the dynamic setting).

This change exposes an issue when we include SCCs in images, namely that the AOT code in SCCs is sensitive the heap geometry and can't tolerate certain changes to the max heap setting. If the current max heap setting is not compatible with the AOT code in the SCC the code won't be used and new code won't be added to the SCC, which can lead to noticeable startup performance fluctuations and degradations.

This set of patches makes changes to 1) populate SCCs with `-Xmx512m`, 2) adds `-Xmx512m` to `IBM_JAVA_OPTIONS` such that by default servers will run with a compatible max heap setting.

### CODE REVIEW

**Comment by vijaysun-omr** [comment]
@arthurdm fyi

**Comment by arthurdm** [comment]
thanks @ymanton / @vijaysun-omr 

One question I have is:   is the JDK 11 have dynamic max heap, do we need to set it to 512 as the PR is doing?   Any chance this can potentially break current JDK 11 which are using more than 512 but are not explicitly setting the max heap size?

**Comment by ymanton** [comment]
> One question I have is: is the JDK 11 have dynamic max heap, do we need to set it to 512 as the PR is doing? Any chance this can potentially break current JDK 11 which are using more than 512 but are not explicitly setting the max heap size?

Yes, there's a chance. If someone is using JDK11, not setting a max heap, using more than 512m of heap space, but always running on a host with lots of free memory such that the JVM chooses a large enough max heap, they will likely see OOM exceptions now where as they did not before.

Having said that, even without this change they can still break if they start running on a host with much less free memory. This change is exposing an existing problem for them more so than creating a new one, but that may not go over well with people who's apps all of a sudden break when nothing else changed.

Longer term we are looking at ways of avoiding this sort of dependency between AOT code and heap geometry, but the short-term alternatives are:

- Choose a much larger max heap for >=JDK11. This might cause a noticeable increase in memory usage for some if we choose a max heap that exceeds what the JVM would have chosen, but there's no way for us to choose a value that will cater to everybody.
- Keep >=JDK11 as it is now and accept the start-up fluctuations.

**Comment by vijaysun-omr** [comment]
Please note that the change to OpenJ9 JDK11 default heap size behaviour itself was a very recent one and arguably is one that could break existing users. 
So, in a sense existing users of JDK11 via this docker image are in fact being shielded by that change via this proposed PR.

**Comment by arthurdm** [comment]
if in the future there will be a less direct dependency on the heap size and the AOT code, I wonder if for now we can simply document that for JDK 11+ if customers are experiencing inconsistent startup times across machines they can set their Xmx to a suitable value?

**Comment by ymanton** [comment]
I've updated the PR to only deal with JDK8; the behaviour on later JDKs is left unchanged.

For JDK8 I've added `-XX:+OriginalJDK8HeapSizeCompatibilityMode` to the JVM options used to build the SCC. This option will revert the new behaviour and keep us to a max heap of 512m when generating the SCC which should give us the most compatible SCC for a small and medium memory scenarios. The option will be on the command line for all JDKs but has no effect on >JDK8.

I'm not adding anything to options used to run the container; this applies only to the options in effect when building the SCC.

> if in the future there will be a less direct dependency on the heap size and the AOT code, I wonder if for now we can simply document that for JDK 11+ if customers are experiencing inconsistent startup times across machines they can set their Xmx to a suitable value?

Done. The README now says they should try a smaller `-Xmx` value. We can't suggest an exact value because the details are tricky, but the AOT code in the SCC should be compatible with the sorts of heaps people tend to use these days (i.e. small and medium) and the limitation shouldn't exist for too long anyway.

**Pull request merged**
