### PR TITLE
Add official Liberty images on Java 11

### PR DESCRIPTION
**Pull request by aguibert**
Adds the following labels:
- `open-liberty:kernel-java11`
- `open-liberty:javaee7-java11`
- `open-liberty:javaee8-java11`
- `open-liberty:microProfile1-java11`
- `open-liberty:microProfile2-java11`
- `open-liberty:springBoot1-java11`
- `open-liberty:springBoot2-java11`
- `open-liberty:webProfile7-java11`
- `open-liberty:webProfile8-java11`

The things that are not a straight copy/paste from the java 8 images are in the second commit. Namely:
 - needed to install wget (must have gotten it from inherited java layer before)
 - needed to create the user home dir `/home/default` to avoid the error 

Note that we do get some warnings on container start right now:
```
$ docker run open-liberty:webProfile8-java11

WARNING: Unknown module: jdk.management.agent specified to --add-exports
WARNING: Unknown module: jdk.attach specified to --add-exports
Launching defaultServer (Open Liberty 19.0.0.5/wlp-1.0.28.cl190520190522-2227) on Eclipse OpenJ9 VM, version 11.0.3+7 (en_US)
...
```
but we these warnings are benign and I can fix them for the next release. The reason for these errors is that we are telling the JVM to open up some modules which only exist in a JDK, and since we are building on a JRE here the modules don't exist.

### CODE REVIEW

**Comment by arthurdm** [comment]
Maybe this PR could be just to rename `community/<tag>/java11/openj9/Dockerfile` to `official/<tag>/java11/openj9/Dockerfile` and then update the `FROM`?

**Comment by naumanna** [comment]
Just saw Arthur's comment.  That's true we should delete the community java 11 images since they would be moving to official.

**Comment by aguibert** [comment]
@arthurdm I didn't take the "move" approach you suggested because I wanted to preserve any differences we may have between the official vs. community images, such as using `wget` instead of `curl` in our official images.

@naumanna I've added another commit which removes the community Java 11 images

**Comment by aguibert** [comment]
added another commit which overlays a patched version of java9.options in the Liberty install, which allows us to avoid the 2 warning messages I mentioned in the OP and gives us a clean server start out of the box

**Comment by aguibert** [comment]
@arthurdm @naumanna I'll leave it up to one of you two to optionally look over the most recent commit I had to amend, and then merge the PR if everything looks to be in order.

**Pull request merged**
