### PR TITLE
Prefer Liberty SCC to OpenJ9 SCC

### LINKED ISSUE #203: New Java SCC causing problems.
I am seeing this new error in the openliberty/daily image. I assume this will hit the official images also soon. There is work to do getting the new java shared class cache working with ours. This causes a decent regression for startup time.

I see this option: -Xshareclasses:name=openj9_system_scc,cacheDir=/opt/java/.scc,readonly,nonFatal

I have already talked to @ymanton about this.
```
docker run openliberty/daily
JVMSHRC226E Error opening shared class cache file
JVMSHRC336E Port layer error code = -102
JVMSHRC337E Platform error message: Permission denied
JVMSHRC840E Failed to start up the shared cache.
JVMSHRC686I Failed to startup shared class cache. Continue without using it as -Xshareclasses:nonfatal is specified
Launching defaultServer (Open Liberty 20.0.0.11/wlp-1.0.46.cl201120200919-1900) on Eclipse OpenJ9 VM, version 1.8.0_265-b01 (en_US)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/keystore.xml
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/open-default-port.xml
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[AUDIT   ] CWWKF0012I: The server installed the following features: [el-3.0, jsp-2.3, servlet-3.1].
[AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 2.319 seconds.
```

### PR DESCRIPTION
**Pull request by ymanton**
OpenJ9 images now ship with an SCC that we can use as a base SCC layer.

Fixes #203

FYI @jdmcclur, can you give this patch a try?

### CODE REVIEW

**Comment by ymanton** [comment]
This patch assumes that we want to use the SCC in the OpenJ9 container as the base SCC layer and add OpenLiberty SCC layers on top. The IBM JDK does not (currently) ship with an SCC so for that case we'll maintain the old behaviour of building the OL SCC layers in the old `/output/.classCache` directory.

**Comment by ymanton** [comment]
Also, I left the older `20.0.0.x` releases alone. Do we want to change those? Are they meant to be forward compatible with later OpenJ9 images?

**Comment by ymanton** [comment]
Added a workaround for the problem mentioned in https://github.com/OpenLiberty/ci.docker/issues/203#issuecomment-700219741 (FYI @jdmcclur). Details are in the patch, smells like a Linux and/or Docker bug, but root cause is not yet clear.

**Comment by ymanton** [comment]
Workaround is insufficient. Subsequent Docker layers hit the same issue. It's possible that applying workarounds at each Docker layer would "fix" it, but at this point it's not worth compounding a less than ideal fix just to get it working so we're going to ignore the OpenJ9 SCC for the time being and continue to build Liberty SCC layers. We can revisit once the root cause of the problem is found. The new patch ignores the incoming SCC settings from the OpenJ9 image and overrides them with the existing Liberty options.

I've also back-ported the changes to the 20.0.0.x releases after getting feedback offline to https://github.com/OpenLiberty/ci.docker/pull/204#issuecomment-699075296.

**Comment by jdmcclur** [comment]
LGTM, also will need a PR for the WebSphere Liberty images, right?

**Comment by ymanton** [comment]
Missed updating `populate_scc.sh` in the `20.0.0.x` directories; fixed and re-pushed.

> LGTM, also will need a PR for the WebSphere Liberty images, right?

Yes, I have a PR for that which I'll open once this patch starts looking final.

**Comment by KokinSSJ** [comment]
Hi, I'm new to Liberty but I've found this SCC layer problem when running latest ubi and also problem #203. 
I agree with @ymanton  changes, adoptopenjdk image is setting OPENJ9_JAVA_OPTIONS variable which is used  by liberty in bin/server startup but  IBM_JAVA_OPTIONS is ignored.

**Comment by mpirvu** [comment]
What happens if the user wants to set his/her own options when running the container with `-e OPENJ9_JAVA_OPTIONS="..." `? Does this overwrite the options for SCC?

**Comment by ymanton** [comment]
Yes, it will overwrite the existing env vars. If the user wants to only add to the existing options they'll have to retrieve the existing ones and append theirs. This is true for the OpenJ9 images as well.

**Comment by mpirvu** [comment]
> This is true for the OpenJ9 images as well.

Which is why I opened https://github.com/AdoptOpenJDK/openjdk-docker/issues/402

> If the user wants to only add to the existing options they'll have to retrieve the existing ones and append theirs.

This is far from ideal. As soon as all the usability fixes get delivered at adopt we need to revert this PR.

**Comment by mpirvu** [comment]
@arthurdm This PR is ready for your review. Thanks

**Review by arthurdm — APPROVED** [review]
LGTM, thanks everyone

**Pull request merged**
